spring:
  application:
    name: moi-jang-backend

  datasource:
    url: jdbc:mysql://localhost:3306/testmysql?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pqpq1234

  sql:
    init:
      mode: always

  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/api/v1/oauth/code/{registrationId}"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent

logging:
  level:
    org.springframework.security: DEBUG

server:
  forward-headers-strategy: framework

scalar:
  page-title: "Moi Jang API References"
  favicon: "/api/favicon.ico"
  dark-mode: true

springdoc:
  api-docs:
    path: "/api/v3/api-docs"
  swagger-ui:
    path: "/api/swagger-ui.html"
